apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqli-detection-api
  namespace: sqli-detection
  labels:
    app: sqli-detection-api
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sqli-detection-api
  template:
    metadata:
      labels:
        app: sqli-detection-api
        tier: backend
    spec:
      containers:
      - name: sqli-detection-api
        image: sqli-detection-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: sqli-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: sqli-config
              key: API_PORT
        - name: DATABASE_URL
          value: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgres-service:5432/$(POSTGRES_DB)"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqli-secrets
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: sqli-config
              key: POSTGRES_DB
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: sqli-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health/liveness
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health/readiness
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: sqli-detection-api-service
  namespace: sqli-detection
  labels:
    app: sqli-detection-api
spec:
  selector:
    app: sqli-detection-api
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sqli-detection-api-ingress
  namespace: sqli-detection
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "60s"
spec:
  rules:
  - host: api.sqli-detection.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sqli-detection-api-service
            port:
              number: 3001
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sqli-detection-api-hpa
  namespace: sqli-detection
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sqli-detection-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
