apiVersion: v1
kind: Namespace
metadata:
  name: sqli-detection
  labels:
    name: sqli-detection
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sqli-config
  namespace: sqli-detection
data:
  NODE_ENV: "production"
  POSTGRES_DB: "sqli_detection"
  POSTGRES_USER: "postgres"
  API_PORT: "3001"
  RAG_PORT: "3002"
---
apiVersion: v1
kind: Secret
metadata:
  name: sqli-secrets
  namespace: sqli-detection
type: Opaque
data:
  postgres-password: cGFzc3dvcmQxMjM=  # password123
  openai-api-key: ZGVtby1rZXk=  # demo-key
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: sqli-detection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sqli-detection
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: sqli-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: sqli-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqli-secrets
              key: postgres-password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: sqli-detection
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
