apiVersion: apps/v1
kind: Deployment
metadata:
  name: langchain-rag
  namespace: sqli-detection
  labels:
    app: langchain-rag
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: langchain-rag
  template:
    metadata:
      labels:
        app: langchain-rag
        tier: backend
    spec:
      containers:
      - name: langchain-rag
        image: langchain-rag:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: sqli-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: sqli-config
              key: RAG_PORT
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: sqli-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/v1/rag/status
            port: 3002
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/rag/status
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: langchain-rag-service
  namespace: sqli-detection
  labels:
    app: langchain-rag
spec:
  selector:
    app: langchain-rag
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: langchain-rag-ingress
  namespace: sqli-detection
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rate-limit: "50"
    nginx.ingress.kubernetes.io/rate-limit-window: "60s"
spec:
  rules:
  - host: rag.sqli-detection.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: langchain-rag-service
            port:
              number: 3002
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: langchain-rag-hpa
  namespace: sqli-detection
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: langchain-rag
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
